module.exports.names = [
    "Abby",
    "Angel",
    "Annie",
    "Baby",
    "Bailey",
    "Bandit",
    "Bear",
    "Bella",
    "Bob",
    "Boo",
    "Boots",
    "Bubba",
    "Buddy",
    "Buster",
    "Cali",
    "Callie",
    "Casper",
    "Charlie",
    "Chester",
    "Chloe",
    "Cleo",
    "Coco",
    "Cookie",
    "Cuddles",
    "Daisy",
    "Dusty",
    "Felix",
    "Fluffy",
    "Garfield",
    "George",
    "Ginger",
    "Gizmo",
    "Gracie",
    "Harley",
    "Jack",
    "Jasmine",
    "Jasper",
    "Kiki",
    "Kitty",
    "Leo",
    "Lilly",
    "Lily",
    "Loki",
    "Lola",
    "Lucky",
    "Lucy",
    "Luna",
    "Maggie",
    "Max",
    "Mia",
    "Midnight",
    "Milo",
    "Mimi",
    "Miss kitty",
    "Missy",
    "Misty",
    "Mittens",
    "Molly",
    "Muffin",
    "Nala",
    "Oliver",
    "Oreo",
    "Oscar",
    "Patches",
    "Peanut",
    "Pepper",
    "Precious",
    "Princess",
    "Pumpkin",
    "Rascal",
    "Rocky",
    "Sadie",
    "Salem",
    "Sam",
    "Samantha",
    "Sammy",
    "Sasha",
    "Sassy",
    "Scooter",
    "Shadow",
    "Sheba",
    "Simba",
    "Simon",
    "Smokey",
    "Snickers",
    "Snowball",
    "Snuggles",
    "Socks",
    "Sophie",
    "Spooky",
    "Sugar",
    "Tiger",
    "Tigger",
    "Tinkerbell",
    "Toby",
    "Trouble",
    "Whiskers",
    "Willow",
    "Zoe",
    "Zoey"
]

module.exports.breeds = [
    "Abyssinian",
    "Aegean",
    "American Curl",
    "American Bobtail",
    "American Shorthair",
    "American Wirehair",
    "Arabian Mau",
    "Australian Mist",
    "Asian",
    "Asian Semi-longhair",
    "Balinese",
    "Bambino",
    "Bengal",
    "Birman",
    "Bombay",
    "Brazilian Shorthair",
    "British Semi-longhair",
    "British Shorthair",
    "British Longhair",
    "Burmese",
    "Burmilla",
    "California Spangled",
    "Chantilly-Tiffany",
    "Chartreux",
    "Chausie",
    "Cheetoh",
    "Colorpoint Shorthair",
    "Cornish Rex",
    "Cymric",
    "Cyprus",
    "Devon Rex",
    "Donskoy",
    "Dragon Li",
    "Dwarf cat",
    "Egyptian Mau",
    "European Shorthair",
    "Exotic Shorthair",
    "Foldex",
    "German Rex",
    "Havana Brown",
    "Highlander",
    "Himalayan",
    "Japanese Bobtail",
    "Javanese",
    "Karelian Bobtail",
    "Khao Manee",
    "Korat",
    "Korean Bobtail",
    "Korn Ja",
    "Kurilian Bobtail",
    "LaPerm",
    "Lykoi",
    "Maine Coon",
    "Manx",
    "Mekong Bobtail",
    "Minskin",
    "Munchkin",
    "Nebelung",
    "Napoleon",
    "Norwegian Forest cat",
    "Ocicat",
    "Ojos Azules",
    "Oregon Rex",
    "Oriental Bicolor",
    "Oriental Shorthair",
    "Oriental Longhair",
    "PerFold",
    "Persian (Modern Persian Cat)",
    "Persian (Traditional Persian Cat)",
    "Peterbald",
    "Pixie-bob",
    "Raas",
    "Ragamuffin",
    "Ragdoll",
    "Russian Blue",
    "Russian White, Black and Tabby",
    "Sam Sawet",
    "Savannah",
    "Scottish Fold",
    "Selkirk Rex",
    "Serengeti",
    "Serrade petit",
    "Siamese",
    "Siberian",
    "Singapura",
    "Snowshoe",
    "Sokoke",
    "Somali",
    "Sphynx",
    "Suphalak",
    "Thai",
    "Thai Lilac",
    "Tonkinese",
    "Toyger",
    "Turkish Angora",
    "Turkish Van",
    "Ukrainian Levkoy"
]